MaxEventSize = 0 # value 0 unlimit the maximum event size that can be sent to message bus or core-data.

[Writable]
LogLevel = "INFO"

[Registry]
Host = "192.168.110.223"
Port = 8500
Type = "consul"

[Clients]
  [Clients.core-metadata]
  Protocol = "http"
  Host = "192.168.110.223"
  Port = 59881

[MessageBus]
Protocol = "redis"
Host = "192.168.110.223"
Port = 6379
Type = "redis"
AuthMode = ""  # required for redis messagebus (secure or insecure).
SecretName = "redisdb"
  [MessageBus.Topics]
  PublishTopicPrefix = "edgex/events/device" # /<device-profile-name>/<device-name>/<source-name> will be added to this Publish Topic prefix
  CommandRequestTopic = "edgex/device/command/request/device-plc/#"   # subscribing for inbound command requests
  CommandResponseTopicPrefix = "edgex/device/command/response"   # publishing outbound command responses; <device-service>/<device-name>/<command-name>/<method> will be added to this publish topic prefix
  SystemEventTopic = "edgex/system-events/core-metadata/device/+/device-plc/#"
  [MessageBus.Optional]
  # Default MQTT Specific options that need to be here to enable environment variable overrides of them
  # Client Identifiers
  ClientId = "device-plc"
  # Connection information
  Qos = "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
  KeepAlive = "10" # Seconds (must be 2 or greater)
  Retained = "false"
  AutoReconnect = "true"
  ConnectTimeout = "5" # Seconds
  SkipCertVerify = "false" # Only used if Cert/Key file or Cert/Key PEMblock are specified

